services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
    ports:
      - 9090:9090
    container_name: prometheus
  node_exporter:
    image: prom/node-exporter
    container_name: node_exporter
  grafana:
    image: grafana/grafana-oss:9.3.6
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
volumes:
  grafana_data:
